#!/bin/bash

#Liam Fotheringham - 2595981F

echo "Colouring $1 graph..."

filename=$1

#Apply edge colours to graph
edgepaint "$filename" > "${filename::-3}"_Coloured.gv

#Produce graph drawing
neato -n2 -Tpng "${filename::-3}"_Coloured.gv -o "${filename::-3}"_Coloured.png

echo "All Done!"