#!/bin/bash

#Liam Fotheringham - 2595981F

echo "Highlighting nodes $1 graph..."

filename=$1
folder_name="${filename::-12}"
mkdir -p "$folder_name/graphs/" #Create directory for graphs
mkdir -p "$folder_name/images/" #Create directory for graph drawings

###############################
# Hide node number labels     #
###############################

for ((i = 1; i <= $2; i++)); do
    no_label_code="$no_label_code$i[label=\"\"]"$'\n'
done

#################################################################################################
# Loop through each node and create graph and graph drawing where nodes are highlighted         #
#################################################################################################

for ((i = 1; i <= $2; i++)); do

    highlighted_filename="${filename::-12}_$i.gv" 

    cp $filename "$folder_name/graphs/$highlighted_filename" #Copy the graph structure to the graph folder

    #Append highlight node code to end of file
    echo "$no_label_code" >> "$folder_name/graphs/$highlighted_filename"
    echo "$i[style=filled, fillcolor=cornflowerblue]" >> "$folder_name/graphs/$highlighted_filename"
    echo "}" >> "$folder_name/graphs/$highlighted_filename"

    #Create graph drawing
    if [ $3 == "neato" ]
    then
        
        #Draw graph using neato layout
        neato -n2 -Tpng "$folder_name/graphs/$highlighted_filename" -o "$folder_name/images/${highlighted_filename::-3}".png

    elif [ $3 == "sfdp" ]
    then

        #Draw graph using (s)fdp layout
        sfdp -Tpng "$folder_name/graphs/$highlighted_filename" -o "$folder_name/images/${highlighted_filename::-3}".png

    else
        echo "does not recognise command"
    fi
            
done

echo "All Done!"